version: "3"
services:
  node-app:
    # build context
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules #anonumous volume
    environment:
      - PORT=3000

    # environment variable file
    # env_file:
    #   - ./.env
